name: League Season Announcements

on:
  workflow_dispatch:

jobs:
  announce:
    runs-on: ubuntu-latest
    steps:
      - name: Send Discord Webhook
        env:
          WEBHOOK_URL: ${{ secrets.DISCORD_LEAGUE_ANNOUNCEMENTS }}
        run: curl -H "Content-Type: application/json" -X POST -d "{\"content\":\"ACFA League test: GitHub Actions is connected successfully.\"}" "$WEBHOOK_URL"
